JobBoard.MVC.UI/Controllers/ApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobBoard.Data.EF;
using Microsoft.AspNet.Identity;

namespace JobBoard.MVC.UI.Controllers
{
    [Authorize]
    public class ApplicationsController : Controller
    {
        private JobBoardEntities db = new JobBoardEntities();

        // GET: Applications
        public ActionResult Index()
        {
            //defualt to let users is only thier applications
            string userId = User.Identity.GetUserId();
            var applications = db.Applications.Include(a => a.ApplicationStatu).Include(a => a.OpenPosition).Include(a => a.UserDetail).Where(a => a.UserId == userId);

            //admin can see all summited application
            if (User.IsInRole("Admin"))
            {
                applications = db.Applications.Include(a => a.ApplicationStatu).Include(a => a.OpenPosition).Include(a => a.UserDetail);
                return View(applications.ToList());
            }

            //manager can see thier apps and apps summited to there location
            if (User.IsInRole("Manager"))
            {
                applications = db.Applications.Include(a => a.ApplicationStatu).Include(a => a.OpenPosition).Include(a => a.UserDetail).Where(a => a.OpenPosition.Location.ManagerId == userId || a.UserId == userId);
                return View(applications.ToList());
            }

            return View(applications.ToList());
        }

        public ActionResult SummitedApplications(int? id)
        {
            //defaulted to user seeing there application 
            string userId = User.Identity.GetUserId();
            var applications = db.Applications.Include(a => a.ApplicationStatu).Include(a => a.OpenPosition).Include(a => a.UserDetail).Where(a => a.OpenPosition.Location.ManagerId == userId);

            //check if a id for openpostions was passed back
            if (id == null)
            {
                if (User.IsInRole("Admin"))
                {
                    applications = db.Applications.Include(a => a.ApplicationStatu).Include(a => a.OpenPosition).Include(a => a.UserDetail);
                    return View(applications.ToList());
                }

            }
            //if openpostions id was passed back only give the summited application back to the view
            else
            {
                if (User.IsInRole("Admin"))
                {
                    applications = db.Applications.Include(a => a.ApplicationStatu).Include(a => a.OpenPosition).Include(a => a.UserDetail).Where(a => a.OpenPositionId == id);
                    return View(applications.ToList());
                }
                //managers can only see application for thier location
                if (User.IsInRole("Manager"))
                {
                    applications = db.Applications.Include(a => a.ApplicationStatu).Include(a => a.OpenPosition).Include(a => a.UserDetail).Where(a => a.OpenPosition.Location.ManagerId == userId && a.OpenPositionId == id);
                    return View(applications.ToList());
                }
            }

            return View(applications.ToList());
        }

        // GET: Applications/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Application application = db.Applications.Find(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            return View(application);
        }

        // GET: Applications/Create
        public ActionResult Create()
        {
            ViewBag.ApplicationStatusID = new SelectList(db.ApplicationStatus, "ApplicationStatusId", "StatusName");
            ViewBag.OpenPositionId = new SelectList(db.OpenPositions, "OpenPositionId", "OpenPositionId");
            ViewBag.UserId = new SelectList(db.UserDetails, "UserID", "FirstName");
            return View();
        }

        // POST: Applications/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ApplicationId,UserId,OpenPositionId,ApplicationDate,ManagerNotes,ApplicationStatusID,ResumeFilename")] Application application)
        {
            if (ModelState.IsValid)
            {
                db.Applications.Add(application);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ApplicationStatusID = new SelectList(db.ApplicationStatus, "ApplicationStatusId", "StatusName", application.ApplicationStatusID);
            ViewBag.OpenPositionId = new SelectList(db.OpenPositions, "OpenPositionId", "OpenPositionId", application.OpenPositionId);
            ViewBag.UserId = new SelectList(db.UserDetails, "UserID", "FirstName", application.UserId);
            return View(application);
        }

        // GET: Applications/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Application application = db.Applications.Find(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            ViewBag.ApplicationStatusID = new SelectList(db.ApplicationStatus, "ApplicationStatusId", "StatusName", application.ApplicationStatusID);
            ViewBag.OpenPositionId = new SelectList(db.OpenPositions, "OpenPositionId", "OpenPositionId", application.OpenPositionId);
            ViewBag.UserId = new SelectList(db.UserDetails, "UserID", "FirstName", application.UserId);
            return View(application);
        }

        // POST: Applications/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ApplicationId,UserId,OpenPositionId,ApplicationDate,ManagerNotes,ApplicationStatusID,ResumeFilename")] Application application)
        {
            if (ModelState.IsValid)
            {
                db.Entry(application).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ApplicationStatusID = new SelectList(db.ApplicationStatus, "ApplicationStatusId", "StatusName", application.ApplicationStatusID);
            ViewBag.OpenPositionId = new SelectList(db.OpenPositions, "OpenPositionId", "OpenPositionId", application.OpenPositionId);
            ViewBag.UserId = new SelectList(db.UserDetails, "UserID", "FirstName", application.UserId);
            return View(application);
        }

        // GET: Applications/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Application application = db.Applications.Find(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            return View(application);
        }

        // POST: Applications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Application application = db.Applications.Find(id);
            db.Applications.Remove(application);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JobBoard.MVC.UI/Controllers/OpenPositionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobBoard.Data.EF;
using JobBoard.MVC.UI.Models;
using Microsoft.AspNet.Identity;

namespace JobBoard.MVC.UI.Controllers
{
    public class OpenPositionsController : Controller
    {
        private JobBoardEntities db = new JobBoardEntities();

        // GET: OpenPositions
        public ActionResult Index(string openFiltered)
        {
            ViewBag.OpenFiltered = new SelectList(db.OpenPositions.Select(x => x.Location.City).Distinct());
            var openPositions = db.OpenPositions.Include(o => o.Location).Include(o => o.Position);
            if (string.IsNullOrEmpty(openFiltered))
            {
                return View(openPositions.ToList());
            }
            else
            {
                var filterOpenPositions = (from o in openPositions where o.Location.City.ToLower().Contains(openFiltered.ToLower()) select o).ToList();
                return View(filterOpenPositions);
            }
            
        }

        // GET: OpenPositions/Details/5
        public ActionResult Details(int? id)
        {
            //check to see if user has already applied
            string userId = User.Identity.GetUserId();
            bool applied = false;
            var apps = db.Applications.Where(y => y.OpenPositionId == id).ToList();
            foreach (var x in apps)
            {
                if (x.UserId == userId)
                {
                    applied = true;
                }
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OpenPosition openPosition = db.OpenPositions.Find(id);
            if (openPosition == null)
            {
                return HttpNotFound();
            }
            ViewBag.Hasapplied = applied;
            return View(openPosition);
        }

        [HttpPost]
        public ActionResult Details(int id)
        {
            string userId = User.Identity.GetUserId();
            UserDetail userDet = db.UserDetails.Find(userId);
            Application newApp = new Application();
            newApp.UserId = userId;
            newApp.ApplicationDate = DateTime.Now;
            newApp.OpenPositionId = id;
            newApp.ResumeFilename = userDet.ResumeFileName;
            newApp.ApplicationStatusID = 5;

            db.Applications.Add(newApp);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: OpenPositions/Create
        [Authorize(Roles = "Admin, Manager")]
        public ActionResult Create()
        {
            ViewBag.LocationId = new SelectList(db.Locations, "LocationId", "StoreNumber");
            ViewBag.PositionId = new SelectList(db.Positions, "PositionId", "Title");
            return View();
        }

        // POST: OpenPositions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OpenPositionId,LocationId,PositionId,CloseDate,Internal")] OpenPosition openPosition)
        {
            if (ModelState.IsValid)
            {
                db.OpenPositions.Add(openPosition);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LocationId = new SelectList(db.Locations, "LocationId", "StoreNumber", openPosition.LocationId);
            ViewBag.PositionId = new SelectList(db.Positions, "PositionId", "Title", openPosition.PositionId);
            return View(openPosition);
        }

        // GET: OpenPositions/Edit/5
        [Authorize(Roles = "Admin, Manager")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OpenPosition openPosition = db.OpenPositions.Find(id);
            if (openPosition == null)
            {
                return HttpNotFound();
            }
            ViewBag.LocationId = new SelectList(db.Locations, "LocationId", "StoreNumber", openPosition.LocationId);
            ViewBag.PositionId = new SelectList(db.Positions, "PositionId", "Title", openPosition.PositionId);
            return View(openPosition);
        }

        // POST: OpenPositions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OpenPositionId,LocationId,PositionId,CloseDate,Internal")] OpenPosition openPosition)
        {
            if (ModelState.IsValid)
            {
                db.Entry(openPosition).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LocationId = new SelectList(db.Locations, "LocationId", "StoreNumber", openPosition.LocationId);
            ViewBag.PositionId = new SelectList(db.Positions, "PositionId", "Title", openPosition.PositionId);
            return View(openPosition);
        }

        // GET: OpenPositions/Delete/5
        [Authorize(Roles = "Admin, Manager")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OpenPosition openPosition = db.OpenPositions.Find(id);
            if (openPosition == null)
            {
                return HttpNotFound();
            }
            return View(openPosition);
        }

        // POST: OpenPositions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OpenPosition openPosition = db.OpenPositions.Find(id);
            db.OpenPositions.Remove(openPosition);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JobBoard.MVC.UI/Views/OpenPositions/Create.cshtml
@model JobBoard.Data.EF.OpenPosition

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Open Position</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.LocationId, "Store Number", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LocationId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocationId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PositionId, "Position", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PositionId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PositionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CloseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CloseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CloseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Internal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Internal)
                    @Html.ValidationMessageFor(model => model.Internal, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>$(function () {
            $("#CloseDate").datepicker();
        });</script>
}

JobBoard.MVC.UI/Views/OpenPositions/Delete.cshtml
@model JobBoard.Data.EF.OpenPosition

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OpenPosition</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CloseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CloseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Internal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Internal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location.StoreNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location.StoreNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position.Title)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

JobBoard.MVC.UI/Views/OpenPositions/Details.cshtml
@model JobBoard.Data.EF.OpenPosition
@{
    ViewBag.Title = "Details";
}
<h2>Details</h2>

@using (Html.BeginForm())
{
    <div>
        <h4>Open Position</h4>
        <hr />
        @if (Request.IsAuthenticated && ViewBag.Hasapplied == false)
        {
            <div>
                <div style="background-color: white; border: none; border-radius: 0px;" id="dialog" title="Resume">
                    <p>Ensure your resume is up to date before applying for this Potions. You can upload a new resume if needed in your User settings above.</p>
                </div>
            </div>
        }
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.CloseDate)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.CloseDate)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Location.StoreNumber)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Location.StoreNumber)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Position.Title)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Position.Title)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Position.Department)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Position.Department.DepartmentName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Position.JobDescription)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Position.JobDescription)
            </dd>
        </dl>
        @if (ViewBag.Hasapplied == true)
        {
            <label style="font-weight: bolder">YOU HAVE ALREADY APPLIED FOR THIS POSITION!</label>
        }
        @if (Request.IsAuthenticated && ViewBag.Hasapplied == false)
        {
            <div class="form-actions"><input type="submit" value="Apply" class="btn btn-default" /></div>
        }
        @if (User.IsInRole("Admin") || User.IsInRole("Manager"))
        {
            <div><br /><a href="@Url.Action("SummitedApplications", "Applications", new { id = Model.OpenPositionId })" class="btn btn-default">Summited Applications</a></div>
        }
    </div>
}

<p>
    <br />
    @if (User.IsInRole("Admin") || User.IsInRole("Manager"))
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.OpenPositionId }) <span> | </span>
    }
    @Html.ActionLink("Back to List", "Index")
</p>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(function () {
            $("#dialog").dialog();
        });
    </script>
}

JobBoard.MVC.UI/Views/OpenPositions/Edit.cshtml
@model JobBoard.Data.EF.OpenPosition
@{
    ViewBag.Title = "Edit";
}
<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>OpenPosition</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OpenPositionId)
        <div class="form-group">
            @Html.LabelFor(model => model.LocationId, "LocationId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LocationId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocationId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PositionId, "PositionId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PositionId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PositionId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CloseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CloseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CloseDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Internal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Internal)
                    @Html.ValidationMessageFor(model => model.Internal, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
    $(function () {
            $("#CloseDate").datepicker();
        });
    </script>
}

JobBoard.MVC.UI/Views/OpenPositions/Index.cshtml
@model IEnumerable<JobBoard.Data.EF.OpenPosition>
@{
    ViewBag.Title = "Index";
}
<h2>Open Postions</h2>
<div>
    <div>
        <h4>Filter by Location</h4>
        @using (Html.BeginForm("Index", "OpenPositions", FormMethod.Get))
        {
            <div class="row">
                <input type="submit" value="Go" class=" btn btn-primary col-md-1" />
                @Html.DropDownList("OpenFiltered", null, "[ - Choose Location - ]", new { @class = "form-control col-md-3" })
            </div>
        }
    </div>
</div>

@if (Model.Count() == 0)
{
    <h4>Nothing currenly open at @Request.QueryString["OpenFiltered"].ToString()</h4>
}
else
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Position.Title)
            </th>
            <th class="hideMobile">
                @Html.DisplayNameFor(model => model.Position.Department)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location.City)
            </th>
            <th class="hideMobile">
                @Html.DisplayNameFor(model => model.CloseDate)
            </th>
            <th class="hideMobile"></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.Position.Title, "Details", new { id = item.OpenPositionId })
                </td>
                <td class="hideMobile">
                    @Html.DisplayFor(modelItem => item.Position.Department.DepartmentName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Location.City)
                </td>
                <td class="hideMobile">
                    @Html.DisplayFor(modelItem => item.CloseDate)
                </td>
                <td class="hideMobile">
                    @if (User.IsInRole("Admin") || User.IsInRole("Manager"))
                    {
                        @Html.ActionLink("Edit", "Edit", new { id = item.OpenPositionId })<span> | </span>
                        @Html.ActionLink("Delete", "Delete", new { id = item.OpenPositionId })
                    }
                </td>
            </tr>
        }
    </table>
}