JobBoard.MVC.UI/Controllers/ApplicationStatusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobBoard.Data.EF;

namespace JobBoard.MVC.UI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ApplicationStatusController : Controller
    {
        private JobBoardEntities db = new JobBoardEntities();

        // GET: ApplicationStatus
        public ActionResult Index()
        {
            return View(db.ApplicationStatus.ToList());
        }

        // GET: ApplicationStatus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationStatu applicationStatu = db.ApplicationStatus.Find(id);
            if (applicationStatu == null)
            {
                return HttpNotFound();
            }
            return View(applicationStatu);
        }

        // GET: ApplicationStatus/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ApplicationStatus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ApplicationStatusId,StatusName,StatusDescription")] ApplicationStatu applicationStatu)
        {
            if (ModelState.IsValid)
            {
                db.ApplicationStatus.Add(applicationStatu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(applicationStatu);
        }

        // GET: ApplicationStatus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationStatu applicationStatu = db.ApplicationStatus.Find(id);
            if (applicationStatu == null)
            {
                return HttpNotFound();
            }
            return View(applicationStatu);
        }

        // POST: ApplicationStatus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ApplicationStatusId,StatusName,StatusDescription")] ApplicationStatu applicationStatu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(applicationStatu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(applicationStatu);
        }

        // GET: ApplicationStatus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationStatu applicationStatu = db.ApplicationStatus.Find(id);
            if (applicationStatu == null)
            {
                return HttpNotFound();
            }
            return View(applicationStatu);
        }

        // POST: ApplicationStatus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ApplicationStatu applicationStatu = db.ApplicationStatus.Find(id);
            db.ApplicationStatus.Remove(applicationStatu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JobBoard.MVC.UI/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobBoard.Data.EF;

namespace JobBoard.MVC.UI.Controllers
{
    [Authorize(Roles = "Admin, Manager")]
    public class DepartmentsController : Controller
    {
        private JobBoardEntities db = new JobBoardEntities();

        // GET: Departments
        public ActionResult Index()
        {
            return View(db.Departments.ToList());
        }

        // GET: Departments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // GET: Departments/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Departments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DepartmetntId,DepartmentName")] Department department)
        {
            if (ModelState.IsValid)
            {
                db.Departments.Add(department);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(department);
        }

        // GET: Departments/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // POST: Departments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DepartmetntId,DepartmentName")] Department department)
        {
            if (ModelState.IsValid)
            {
                db.Entry(department).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(department);
        }

        // GET: Departments/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // POST: Departments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Department department = db.Departments.Find(id);
            db.Departments.Remove(department);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JobBoard.MVC.UI/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobBoard.Data.EF;

namespace JobBoard.MVC.UI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class LocationsController : Controller
    {
        private JobBoardEntities db = new JobBoardEntities();

        // GET: Locations
        public ActionResult Index()
        {
            var locations = db.Locations.Include(l => l.UserDetail);
            return View(locations.ToList());
        }

        // GET: Locations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // GET: Locations/Create
        public ActionResult Create()
        {
            ViewBag.ManagerId = new SelectList(db.UserDetails, "UserID", "FirstName");
            return View();
        }

        // POST: Locations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LocationId,StoreNumber,City,State,ManagerId")] Location location)
        {
            if (ModelState.IsValid)
            {
                db.Locations.Add(location);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ManagerId = new SelectList(db.UserDetails, "UserID", "FirstName", location.ManagerId);
            return View(location);
        }

        // GET: Locations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            ViewBag.ManagerId = new SelectList(db.UserDetails, "UserID", "FirstName", location.ManagerId);
            return View(location);
        }

        // POST: Locations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LocationId,StoreNumber,City,State,ManagerId")] Location location)
        {
            if (ModelState.IsValid)
            {
                db.Entry(location).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ManagerId = new SelectList(db.UserDetails, "UserID", "FirstName", location.ManagerId);
            return View(location);
        }

        // GET: Locations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // POST: Locations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Location location = db.Locations.Find(id);
            db.Locations.Remove(location);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JobBoard.MVC.UI/Controllers/PositionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobBoard.Data.EF;

namespace JobBoard.MVC.UI.Controllers
{
    [Authorize(Roles = "Admin, Manager")] 
    public class PositionsController : Controller
    {
        private JobBoardEntities db = new JobBoardEntities();

        // GET: Positions
        public ActionResult Index()
        {
            var positions = db.Positions.Include(p => p.Department);
            return View(positions.ToList());
        }

        // GET: Positions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Position position = db.Positions.Find(id);
            if (position == null)
            {
                return HttpNotFound();
            }
            return View(position);
        }

        // GET: Positions/Create
        public ActionResult Create()
        {
            ViewBag.DepartmentID = new SelectList(db.Departments, "DepartmetntId", "DepartmentName");
            return View();
        }

        // POST: Positions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PositionId,Title,JobDescription,DepartmentID")] Position position)
        {
            if (ModelState.IsValid)
            {
                db.Positions.Add(position);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DepartmentID = new SelectList(db.Departments, "DepartmetntId", "DepartmentName", position.DepartmentID);
            return View(position);
        }

        // GET: Positions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Position position = db.Positions.Find(id);
            if (position == null)
            {
                return HttpNotFound();
            }
            ViewBag.DepartmentID = new SelectList(db.Departments, "DepartmetntId", "DepartmentName", position.DepartmentID);
            return View(position);
        }

        // POST: Positions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PositionId,Title,JobDescription,DepartmentID")] Position position)
        {
            if (ModelState.IsValid)
            {
                db.Entry(position).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DepartmentID = new SelectList(db.Departments, "DepartmetntId", "DepartmentName", position.DepartmentID);
            return View(position);
        }

        // GET: Positions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Position position = db.Positions.Find(id);
            if (position == null)
            {
                return HttpNotFound();
            }
            return View(position);
        }

        // POST: Positions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Position position = db.Positions.Find(id);
            db.Positions.Remove(position);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JobBoard.MVC.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <!-- Google fonts - Roboto-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,700">
    <link rel="shortcut icon" href="~/Content/imgs/icons.jpg" type="image/x-icon">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/overcast/jquery-ui.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" />
    <!-- Tweaks for older IEs-->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<body>
    @using Microsoft.AspNet.Identity
    <div id="all">
        @*top bar*@
        <div class="top-bar">
            <div class="container">
                <div class="row d-flex align-items-center">
                    <div class="col-md-6 d-md-block d-none">
                        <p>Contact us at +420 777 555 333</p>
                    </div>
                    <div class="col-md-6">
                        <div class="d-flex justify-content-md-end justify-content-between">
                            <ul class="list-inline contact-info d-block d-md-none">
                                <li class="list-inline-item"><a href="#"><i class="fa fa-phone"></i></a></li>
                                <li class="list-inline-item"><a href="#"><i class="fa fa-envelope"></i></a></li>
                            </ul>
                            @if (!Request.IsAuthenticated)
                            {
                                <div class="login"><a href="@Url.Action("Login", "Account")" class="login-btn"><i class="fa fa-sign-in"></i><span class="d-none d-md-inline-block">Sign In</span></a><a href="@Url.Action("Register", "Account")" class="signup-btn"><i class="fa fa-user"></i><span class="d-none d-md-inline-block">Sign Up</span></a></div>
                            }
                            @if (Request.IsAuthenticated)
                            {
                                <div class="login">
                                    <a href="@Url.Action(("Edit/" + User.Identity.GetUserId()) , "UserDetails")" class="login-btn"><i class="fa fa-cog"></i><span class="d-none d-md-inline-block">@User.Identity.Name</span></a>
                                </div>
                                <div class="login">
                                    @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                                    {
                                        @Html.AntiForgeryToken()
                                        <a href="javascript:document.getElementById('logoutForm').submit()" class="signup-btn"><i class="fa fa-sign-out"></i><span class="d-none d-md-inline-block">Log off</span></a>
                                    }
                                </div>
                            }
                            <ul class="social-custom list-inline">
                                <li class="list-inline-item"><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li class="list-inline-item"><a href="#"><i class="fa fa-google-plus"></i></a></li>
                                <li class="list-inline-item"><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li class="list-inline-item"><a href="#"><i class="fa fa-envelope"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @*nav bar*@
        <header class="nav-holder make-sticky">
            <div id="navbar" role="navigation" class="navbar navbar-expand-lg">
                <div class="container">
                    <a href="@Url.Action("Index", "Home")" class="navbar-brand home"><img src="~/Content/imgs/JobBoardLogo.jpg" alt="Universal logo" id="logosize" class="d-none d-md-inline-block"><img src="~/Content/imgs/JobBoardLogo.jpg" alt="Universal logo"  id="logosize" class="d-inline-block d-md-none"><span class="sr-only">Universal - go to homepage</span></a>
                    <button type="button" data-toggle="collapse" data-target="#navigation" class="navbar-toggler btn-template-outlined"><span class="sr-only">Toggle navigation</span><i class="fa fa-align-justify"></i></button>
                    <div id="navigation" class="navbar-collapse collapse">
                        <ul class="nav navbar-nav ml-auto">
                            @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                            {
                                <li class="nav-item dropdown">
                                    <a href="javascript: void(0)" data-toggle="dropdown" class="dropdown-toggle"><i class="fa fa-cog"></i>Users<b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li class="dropdown-item"><a href="@Url.Action("Index", "RolesAdmin")" class="nav-link">Roles</a></li>
                                        <li class="dropdown-item"><a href="@Url.Action("Index", "UsersAdmin")" class="nav-link">Users</a></li>
                                        <li class="dropdown-item"><a href="@Url.Action("Index", "UserDetails")" class="nav-link">User Details</a></li>
                                    </ul>
                                </li>
                            }
                            @if (Request.IsAuthenticated && User.IsInRole("Admin") || User.IsInRole("Manager"))
                            {
                                <li class="nav-item dropdown menu-large">
                                    <a href="#" data-toggle="dropdown" class="dropdown-toggle"><i class="fa fa-cog"></i>Manage<b class="caret"></b></a>
                                    <ul class="dropdown-menu megamenu">
                                        <li>
                                            <div class="row">
                                                <div class="col-lg-6"><img src="~/Content/imgs/cube.jpg" alt="" class="img-fluid d-none d-lg-block"></div>
                                                <div class="col-lg-3 col-md-6">
                                                    <ul class="list-unstyled mb-3">
                                                        <li class="nav-item"><a href="@Url.Action("Index", "OpenPositions")" class="nav-link">Edit/Remove Open Positions</a></li>
                                                        <li class="nav-item"><a href="@Url.Action("Create", "OpenPositions")" class="nav-link">Post an Open Position</a></li>
                                                        <li class="nav-item"><a href="@Url.Action("Index", "Positions")" class="nav-link">Edit/Remove Avaible Positions</a></li>
                                                        <li class="nav-item"><a href="@Url.Action("Create", "Positions")" class="nav-link">Create a Position</a></li>
                                                    </ul>
                                                </div>
                                                <div class="col-lg-3 col-md-6">
                                                    <ul class="list-unstyled mb-3">
                                                        <li class="nav-item"><a href="@Url.Action("Index", "Applications")" class="nav-link">View/Update Applications</a></li>

                                                        <li class="nav-item"><a href="@Url.Action("Index", "Departments")" class="nav-link">Departments</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </li>
                            }
                            @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                            {
                                <li class="nav-item dropdown">
                                    <a href="javascript: void(0)" data-toggle="dropdown" class="dropdown-toggle"><i class="fa fa-cog"></i>Admin<b class="caret"></b></a>
                                    <ul class="dropdown-menu">

                                        <li class="dropdown-item"><a href="@Url.Action("Create", "Locations")" class="nav-link">Create a Location</a></li>
                                        <li class="dropdown-item"><a href="@Url.Action("Index", "Locations")" class="nav-link">Edit/Remove Locations</a></li>
                                        <li class="nav-item"><a href="@Url.Action("Create", "Departments")" class="nav-link">Create a Department</a></li>
                                        <li class="dropdown-item"><a href="@Url.Action("Index", "Departments")" class="nav-link">Edit/Remove Departments</a></li>
                                        <li class="dropdown-item dropdown-submenu">
                                            <a id="navbarDropdownMenuLink2" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle">Application Status</a>
                                            <ul aria-labelledby="navbarDropdownMenuLink2" class="dropdown-menu">
                                                <li class="dropdown-item"><a href="@Url.Action("Index", "ApplicationStatus")" class="nav-link">Application Status</a></li>
                                                <li class="dropdown-item"><a href="@Url.Action("Create", "ApplicationStatus")" class="nav-link">Create New Status</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                            }
                            <li class="nav-item dropdown">
                                <a href="javascript: void(0)" data-toggle="dropdown" class="dropdown-toggle">Career Services<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li class="dropdown-item"><a href="@Url.Action("Index", "OpenPositions")" class="nav-link">Open Positions</a></li>
                                    @if (Request.IsAuthenticated)
                                    {
                                        <li class="dropdown-item"><a href="@Url.Action("Index", "Applications")" class="nav-link">Your Applications</a></li>
                                    }
                                    @if (User.IsInRole("Admin") || User.IsInRole("Manager"))
                                    {
                                        <li class="dropdown-item"><a href="@Url.Action("SummitedApplications", "Applications")" class="nav-link">Summited Applications</a></li>
                                    }
                                </ul>
                            </li>
                            <li class="active">
                                <a href="@Url.Action("Contact", "Home")">Contact</a>
                            </li>
                        </ul>
                    </div>
                    <div id="search" class="collapse clearfix">
                        <form role="search" class="navbar-form">
                            <div class="input-group">
                                <input type="text" placeholder="Search" class="form-control"><span class="input-group-btn">
                                    <button type="submit" class="btn btn-template-main"><i class="fa fa-search"></i></button>
                                </span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </header>
        <div class="minHi">
            <div class="container">
                @RenderBody()
            </div>
        </div>
        <footer class="main-footer">
            <div class="copyrights">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-4 text-center-md">
                            <p>&copy; @DateTime.Now.Year Company Name / Ian Whitehill</p>
                        </div>
                        <div class="col-lg-8 text-right text-center-md">
                            <p>Template design by <a href="https://bootstrapious.com/snippets">Bootstrapious </a>&  <a href="https://fity.cz/">Fity</a></p>
                            <!-- Please do not remove the backlink to us unless you purchase the Attribution-free License at https://bootstrapious.com/donate. Thank you. -->
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="https://cdn.jsdelivr.net/jquery.ajax.unobtrusive/3.2.4/jquery.unobtrusive-ajax.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="//cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>